# Generated by Django 4.1.5 on 2023-02-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_credit_payed_credit_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='payed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='credit',
            name='to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
