# Generated by Django 4.1.5 on 2023-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_alter_credit_payed_alter_credit_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='etat',
            field=models.BooleanField(default=0),
        ),
    ]
