# Generated by Django 4.1.5 on 2023-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_credit_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnt_produit',
            name='date',
            field=models.DateField(auto_now_add=True, default='2023-02-17'),
            preserve_default=False,
        ),
    ]
